# PowerShell script to auto-increment build version
# This script increments the build number in pubspec.yaml

$pubspecPath = "pubspec.yaml"

# Read pubspec.yaml
$content = Get-Content $pubspecPath -Raw

# Extract current version (format: version: 1.0.24+24)
if ($content -match 'version:\s*(\d+)\.(\d+)\.(\d+)\+(\d+)') {
    $major = [int]$matches[1]
    $minor = [int]$matches[2]
    $patch = [int]$matches[3]
    $build = [int]$matches[4]

    # Increment patch and build number
    $newPatch = $patch + 1
    $newBuild = $build + 1

    # Create new version string
    $newVersion = "$major.$minor.$newPatch+$newBuild"

    # Replace in content
    $newContent = $content -replace "version:\s*\d+\.\d+\.\d+\+\d+", "version: $newVersion"

    # Save back to pubspec.yaml
    Set-Content -Path $pubspecPath -Value $newContent -NoNewline

    # Get current date (DD.MM.YYYY format)
    $currentDate = Get-Date -Format "dd.MM.yyyy"

    # Create version info file for display
    $versionDisplay = "v1.$newPatch ($currentDate)"
    $versionInfoContent = @"
/// App version constants
/// Auto-generated by increment_version.ps1 - DO NOT EDIT MANUALLY
class AppVersion {
  static const String version = '$versionDisplay';
  static const String buildDate = '$currentDate';
  static const int buildNumber = $newBuild;
}
"@

    # Save version info to Dart file
    $versionFilePath = "lib\core\constants\app_version.dart"
    Set-Content -Path $versionFilePath -Value $versionInfoContent

    Write-Host "✓ Version incremented successfully!" -ForegroundColor Green
    Write-Host "  Old version: $major.$minor.$patch+$build" -ForegroundColor Gray
    Write-Host "  New version: $newVersion" -ForegroundColor Cyan
    Write-Host "  Display as:  $versionDisplay" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Version info saved to: $versionFilePath" -ForegroundColor Gray
}
else {
    Write-Host "Error: Could not parse version from pubspec.yaml" -ForegroundColor Red
    exit 1
}
