// File generated by FlutterFire CLI.
// This is a placeholder file. Run 'flutterfire configure' to generate actual config.
// See FIREBASE_SETUP.md for detailed instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw_HapbrEBvUg_dJHQlnjI_WUKRKHoK0U',
    appId: '1:469599285395:web:68b29d48c3a3a2d8f71d66',
    messagingSenderId: '469599285395',
    projectId: 'klaussified-e304a',
    authDomain: 'klaussified-e304a.firebaseapp.com',
    storageBucket: 'klaussified-e304a.firebasestorage.app',
    measurementId: 'G-JPRKS3284T',
  );

  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6_ZccvEEOsDczZDppW4FOevDVMuIr-uY',
    appId: '1:469599285395:android:4246c665041bc8a5f71d66',
    messagingSenderId: '469599285395',
    projectId: 'klaussified-e304a',
    storageBucket: 'klaussified-e304a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUoO_vT46ZwN9Zc3hAPnf84OCYGX4Tp4',
    appId: '1:469599285395:ios:c76dbdc3d3440e45f71d66',
    messagingSenderId: '469599285395',
    projectId: 'klaussified-e304a',
    storageBucket: 'klaussified-e304a.firebasestorage.app',
    iosClientId: '469599285395-m7mpjr82lka275ave964i63i5fm9q37b.apps.googleusercontent.com',
    iosBundleId: 'me.nairdah.klaussified.klaussified',
  );

}