/// App version constants
/// Auto-generated by increment_version.ps1 - DO NOT EDIT MANUALLY
class AppVersion {
  static const String version = 'v1.025 (11.11.2025)';
  static const String buildDate = '11.11.2025';
  static const int buildNumber = 25;
}
